

-- MANUALLY DROP SCHEMA IF ALREADY EXIST
DROP USER C##_JAVA_JSP CASCADE;

-- MANUALLY CREATE & GRANT SCHEMA
CREATE USER C##_JAVA_JSP IDENTIFIED BY passSFS3434_JAVA_JSP  CONTAINER=ALL;
GRANT ALL PRIVILEGES TO C##_JAVA_JSP;