
BEGIN
    DECLARE
        c INT;

    BEGIN
        SELECT COUNT(*) INTO c FROM USER_TABLES WHERE TABLE_NAME = UPPER('TBL_PARAMETER');
        IF c = 1 THEN
            EXECUTE IMMEDIATE 'DROP TABLE C##_JAVA_JSP.TBL_PARAMETER CASCADE CONSTRAINTS';
        END IF;
    END;

    EXECUTE IMMEDIATE 'CREATE TABLE C##_JAVA_JSP.TBL_PARAMETER (
            "N_ID"                      NUMBER(19,0) NOT NULL PRIMARY KEY,
        	"VCH_NAME"                  VARCHAR2(255 CHAR),
        	"VCH_VALUE"                 VARCHAR2(255 CHAR),
        	"VCH_ACTIONS"               VARCHAR2(255 CHAR),
        	"VCH_LAST_UPDATE_DATE_TIME" VARCHAR2(255 CHAR),
        	"VCH_LAST_UPDATE_USER"      VARCHAR2(255 CHAR),
        	"VCH_HISTORY"               VARCHAR2(255 CHAR)
         )';

END;

-----------

CREATE TABLE C##_JAVA_JSP.TBL_PARAMETER (
            "N_ID"                      NUMBER(19,0) NOT NULL PRIMARY KEY,
        	"VCH_NAME"                  VARCHAR2(255 CHAR),
        	"VCH_VALUE"                 VARCHAR2(255 CHAR),
        	"VCH_ACTIONS"               VARCHAR2(255 CHAR),
        	"VCH_LAST_UPDATE_DATE_TIME" VARCHAR2(255 CHAR),
        	"VCH_LAST_UPDATE_USER"      VARCHAR2(255 CHAR),
        	"VCH_HISTORY"               VARCHAR2(255 CHAR)
         );

-----------

INSERT INTO C##_JAVA_JSP.TBL_PARAMETER (N_ID, VCH_NAME, VCH_VALUE, VCH_ACTIONS, VCH_LAST_UPDATE_DATE_TIME, VCH_LAST_UPDATE_USER, VCH_HISTORY)
VALUES (1, 'Nume tema', 'Dark', 'Edit', '11.11.2021 14:15', 'admin', 'View');

INSERT INTO C##_JAVA_JSP.TBL_PARAMETER (N_ID, VCH_NAME, VCH_VALUE, VCH_ACTIONS, VCH_LAST_UPDATE_DATE_TIME, VCH_LAST_UPDATE_USER, VCH_HISTORY)
VALUES (2, 'HTTP Port', '8088', 'Edit', '11.11.2021 14:15', 'admin', 'View');

INSERT INTO C##_JAVA_JSP.TBL_PARAMETER (N_ID, VCH_NAME, VCH_VALUE, VCH_ACTIONS, VCH_LAST_UPDATE_DATE_TIME, VCH_LAST_UPDATE_USER, VCH_HISTORY)
VALUES (3, 'Timout', '120', 'Edit', '11.11.2021 14:15', 'admin', 'View');

INSERT INTO C##_JAVA_JSP.TBL_PARAMETER (N_ID, VCH_NAME, VCH_VALUE, VCH_ACTIONS, VCH_LAST_UPDATE_DATE_TIME, VCH_LAST_UPDATE_USER, VCH_HISTORY)
VALUES (4, 'Debug level', 'ERROR', 'Edit', '11.11.2021 14:15', 'admin', 'View');

-----------





-----------

CREATE TABLE TBL_PARAMETER (
            "N_ID"                      NUMBER(19,0) NOT NULL PRIMARY KEY,
        	"VCH_NAME"                  VARCHAR2(255 CHAR),
        	"VCH_VALUE"                 VARCHAR2(255 CHAR),
        	"VCH_ACTIONS"               VARCHAR2(255 CHAR),
        	"VCH_LAST_UPDATE_DATE_TIME" VARCHAR2(255 CHAR),
        	"VCH_LAST_UPDATE_USER"      VARCHAR2(255 CHAR),
        	"VCH_HISTORY"               VARCHAR2(255 CHAR)
         );

COMMIT;

-----------

INSERT INTO TBL_PARAMETER (N_ID, VCH_NAME, VCH_VALUE, VCH_ACTIONS, VCH_LAST_UPDATE_DATE_TIME, VCH_LAST_UPDATE_USER, VCH_HISTORY)
VALUES (1, 'Nume tema', 'Dark', 'Edit', '11.11.2021 14:15', 'admin', 'View');

INSERT INTO TBL_PARAMETER (N_ID, VCH_NAME, VCH_VALUE, VCH_ACTIONS, VCH_LAST_UPDATE_DATE_TIME, VCH_LAST_UPDATE_USER, VCH_HISTORY)
VALUES (2, 'HTTP Port', '8088', 'Edit', '11.11.2021 14:15', 'admin', 'View');

INSERT INTO TBL_PARAMETER (N_ID, VCH_NAME, VCH_VALUE, VCH_ACTIONS, VCH_LAST_UPDATE_DATE_TIME, VCH_LAST_UPDATE_USER, VCH_HISTORY)
VALUES (3, 'Timout', '120', 'Edit', '11.11.2021 14:15', 'admin', 'View');

INSERT INTO TBL_PARAMETER (N_ID, VCH_NAME, VCH_VALUE, VCH_ACTIONS, VCH_LAST_UPDATE_DATE_TIME, VCH_LAST_UPDATE_USER, VCH_HISTORY)
VALUES (4, 'Debug level', 'ERROR', 'Edit', '11.11.2021 14:15', 'admin', 'View');

COMMIT;

SELECT * FROM TBL_PARAMETER;

-----------
